- name: create postman location
  file: path=/opt/postman state=directory mode=0755
  register: postmanloc

- name: Download postman
  get_url:
    url: https://dl.pstmn.io/download/latest/linux64
    dest: /opt/postman/postman.tgz
    mode: 0664
  when: postmanloc.changed

- name: Extract Postman
  unarchive:
    remote_src: yes
    src: /opt/postman/postman.tgz
    dest: /opt/postman
  when: postmanloc.changed

- name: create a postman symlink
  file:
    src: /opt/postman/Postman/Postman
    dest: /usr/local/bin/postman
    owner: root
    group: root
    state: link

- name: install git-open
  git: >
    repo=https://github.com/paulirish/git-open.git
    dest={{ localinstallation }}/git-open
    version={{ gitopen_version }}

- name: symlink git-open
  file: >
    src={{localinstallation}}/git-open/git-open
    dest={{ localinstallation }}/bin/git-open
    state=link

- name: install local ansible-docker
  git: >
    repo=https://github.com/ulrichSchreiner/ansible-docker.git
    dest={{ localinstallation }}/ansible-docker
    version=master

- name: create ansible shortcuts
  file: src=/usr/local/ansible-docker/ansible dest=/usr/local/bin/{{item}} mode=0755 state=link
  with_items:
    - ansible
    - ansible-playbook
    - ansible-vault
    - ansible-doc
    - ansible-pull
    - ansible-galaxy
    - ansible-console
    - ansible-config
    - ansible-inventory

- name: create local bin directory
  file: path={{localinstallation}}/bin state=directory mode=0755

- name: install github products
  include_tasks: lib/downloader.yml
  vars:
    product: "{{p}}"
  with_items: "{{gh_products}}"
  loop_control:
    loop_var: p

- name: do arch specific packages after gh-downloads becase wee need yay
  block:
    - name: install base aur packages
      aur: name={{aur_packages}}
      become: yes
      become_user: aur_builder
  when: ansible_distribution == "Archlinux"
