- name: install liquidprompt
  git: >
    repo=https://github.com/nojhan/liquidprompt.git
    dest={{ localinstallation }}/liquidprompt
    version={{ liquidprompt_version }}

- name: install git-open
  git: >
    repo=https://github.com/paulirish/git-open.git
    dest={{ localinstallation }}/git-open
    version={{ gitopen_version }}

- name: symlink git-open
  file: >
    src={{localinstallation}}/git-open/git-open
    dest={{ localinstallation }}/bin/git-open
    state=link

- name: install local ansible-docker
  git: >
    repo=https://github.com/ulrichSchreiner/ansible-docker.git
    dest={{ localinstallation }}/ansible-docker
    version={{ localansible_version }}

- name: create ansible shortcuts
  file: src=/usr/local/ansible-docker/ansible dest=/usr/local/bin/{{item}} mode=0755 state=link
  with_items:
    - ansible
    - ansible-playbook
    - ansible-vault
    - ansible-doc
    - ansible-pull
    - ansible-galaxy

- name: create local bin directory
  file: path={{localinstallation}}/bin state=directory mode=0755

- name: create local bfg directory
  file: path={{localinstallation}}/bfg state=directory mode=0755

- name: install bfg a jar
  get_url: >
    url=http://repo1.maven.org/maven2/com/madgag/bfg/{{bfg_version}}/bfg-{{bfg_version}}.jar
    dest={{localinstallation}}/bfg/bfg-{{bfg_version}}.jar
    mode=0755
    force=no

- name: install bfg command
  template: src=bfg.j2 dest={{localinstallation}}/bin/bfg mode=0755

- name: install swarmcluster as command
  template: src=swarmcluster.j2 dest={{localinstallation}}/bin/swarmcluster mode="0755"

- name: install github products
  include: lib/downloader.yml product={{p}}
  with_items: "{{gh_products}}"
  loop_control:
    loop_var: p
