- name: install liquidprompt
  git: >
    repo=https://github.com/nojhan/liquidprompt.git
    dest={{ localinstallation }}/liquidprompt
    version={{ liquidprompt_version }}

- name: install autoenv
  git: >
    repo=https://github.com/kennethreitz/autoenv.git
    dest={{ localinstallation }}/autoenv
    version={{ autoenv_version }}

- name: install local ansible-docker
  git: >
    repo=https://github.com/ulrichSchreiner/ansible-docker.git
    dest={{ localinstallation }}/ansible-docker
    version={{ localansible_version }}

- name: create ansible shortcuts
  file: src=/usr/local/ansible-docker/ansible dest=/usr/local/bin/{{item}} mode=0755 state=link
  with_items:
    - ansible
    - ansible-playbook
    - ansible-vault
    - ansible-doc
    - ansible-pull
    - ansible-galaxy

- name: create local bin directory
  file: path={{localinstallation}}/bin state=directory mode=0755

- name: install docker-compose as a container
  get_url: >
    url=https://github.com/docker/compose/releases/download/{{docker_compose_version}}/run.sh
    dest={{localinstallation}}/bin/docker-compose
    mode=0755
    force=yes
