- name: install base packages
  apt: name={{item}} state=present
  with_items:
    - "{{base_packages}}"

- name: install liquidprompt
  git: >
    repo=https://github.com/nojhan/liquidprompt.git
    dest=/usr/local/liquidprompt
    version=def86eba38703dd69e655a77ae610923e9a19051

- name: install autoenv
  git: >
    repo=https://github.com/kennethreitz/autoenv.git
    dest=/usr/local/autoenv
    version=efb7e7e9d9c59c6452157b4760b8521b08db705a

- name: add key for nodesource
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

- name: add node repository
  apt_repository: repo='deb https://deb.nodesource.com/{{nodejs_version}} {{ansible_distribution_release}} main' state=present

- name: install nodejs
  apt: name=nodejs state=present
