- name: create go destination path
  file: path={{go_installation}} state=directory mode=0755

- name: download go
  unarchive: >
    src=https://storage.googleapis.com/golang/go{{golang_version}}.linux-amd64.tar.gz
    creates={{go_installation}}/go
    dest={{go_installation}}
    copy=no

- name: create go/appengine destination path
  file: path=goapp_installation state=directory mode=0755

- name: download go appengine
  unarchive: >
    src=https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-{{goapp_version}}.zip
    creates=goapp_installation/go_appengine
    dest=goapp_installation
    copy=no

- name: remove old go installations
  file: path={{go_base}}{{item}} state=absent
  with_items:
    - "{{old_go_versions}}"

- name: remove old goapp installations
  file: path={{goapp_base}}{{item}} state=absent
  with_items:
    - "{{old_goapp_versions}}"
    