# first make sure python2 is installed
# do not gather_facts here, because this only
# works with python2
- hosts: all
  gather_facts: no
  become: yes
  pre_tasks:
   - name: 'install python2'
     raw: apt-get -y install python-simplejson


- include: devtools.yaml
- include: userenv.yaml
