# first make sure python2 is installed
# do not gather_facts here, because this only
# works with python2
- hosts: all
  gather_facts: yes
  become: yes
  pre_tasks:
   - name: 'install python2'
     raw: apt-get -y install python-simplejson
     when: ansible_distribution == "Ubuntu"
   - name: show distribution 
     debug: var=ansible_distribution


- import_playbook: devtools.yaml
- import_playbook: userenv.yaml
