---
 - hosts: all
   gather_facts: no
   become: yes
   pre_tasks:
    - name: 'install python2'
      raw: apt-get -y install python-simplejson

 - hosts: development
   become: yes
   roles:
     - devtools
     - gotools

 - hosts: development
   roles:
     - userenv
