- hosts: all
  gather_facts: yes
  become: yes
  pre_tasks:
   - name: show distribution
     debug: var=ansible_distribution

  roles:
    - kewlfft.aur
    - base
    - devtools

- hosts: all
  roles:
    - userenv
    - finish
