- name: create local go workspace
  file: path=~/go state=directory mode=0755

- name: create local development workspace
  file: path=~/development state=directory mode=0755

- name: create common subdirs
  file: path=~/development/{{item}} state=directory mode=0755
  with_items:
    - src/gitlab.com/globalsafetrack
    - src/github.com/ulrichSchreiner
    - src/bitbucket.com/isw
    - src/bitbucket.com/usc
    - src/git.f-i-ts.de/devops
    - src/git.f-i-ts.de/ize0h88
    - pkg
    - bin

- name: create workspaces for development (github, bitbucket, fits)
  file: path=~/workspaces/{{item}} state=directory mode=0755
  with_items:
    - ulrichSchreiner
    - usc
    - isw
    - ize0h88

- name: create local bin
  file: path=~/bin state=directory mode=0755

- name: create local tools
  file: path=~/tools state=directory mode=0755

- name: make the go directory a GOPATH enabled workspace
  copy: src=goenv dest=~/go/.envrc mode=664

- name: install go tools
  include: lib/goget.yaml
  with_items: "{{gogetable_tools}}"

- name: create environment for sourcing
  template: src=myenv.j2 dest=~/.myenv

- name: source the new environment
  lineinfile: dest=~/.bashrc regexp='^source ~/.myenv' line='source ~/.myenv'

- name: set the npm configuration
  copy: src=npmrc dest=~/.npmrc

- name: check if npm-check-updates is installed
  shell: npm list -g --depth 1 npm-check-updates
  ignore_errors: yes
  register: ncu
  check_mode: False
  changed_when: False

- name: install npm-check-updates if needed
  shell: npm install -g npm-check-updates
  when: ncu.rc != 0

- name: insert/update my local ssh config
  blockinfile:
    create: yes
    mode: "0600"
    dest: ~/.ssh/config
    block: |
      Host *
         ForwardAgent yes

- name: install oh-my-zsh
  git: >
    repo=https://github.com/robbyrussell/oh-my-zsh.git
    dest=~/.oh-my-zsh

- name: install my zshrc
  template: src=zshrc.j2 dest=~/.zshrc

- name: install z
  git: >
    repo=https://github.com/rupa/z.git
    dest=~/tools/z
