- name: create local go workspace
  file: path=~/go state=directory mode=0755

- name: create local development workspace
  file: path=~/development state=directory mode=0755

- name: create common subdirs
  file: path=~/development/{{item}} state=directory mode=0755
  with_items:
    - src/gitlab.com/globalsafetrack
    - src/github.com/ulrichSchreiner
    - src/bitbucket.com/isw
    - src/bitbucket.com/usc
    - src/git.f-i-ts.de/devops
    - src/git.f-i-ts.de/ize0h88
    - pkg
    - bin

- name: create workspaces for development (github, bitbucket, fits)
  file: path=~/workspaces/{{item}} state=directory mode=0755
  with_items:
    - ulrichSchreiner
    - usc
    - isw
    - ize0h88

- name: create local bin
  file: path=~/bin state=directory mode=0755

- name: make the go directory a GOPATH enabled workspace
  copy: src=goenv dest=~/go/.env mode=664

- name: install go tools
  include: lib/goget.yaml
  with_items: "{{gogetable_tools}}"

- name: create environment for sourcing
  template: src=bashenv.j2 dest=~/.bashenv

- name: source the new environment
  lineinfile: dest=~/.bashrc regexp='^source ~/.bashenv' line='source ~/.bashenv'

- name: set the npm configuration
  copy: src=npmrc dest=~/.npmrc

- name: install script to transform a directory to a GOPATH enabled workspace
  template: src=createStdGoWS dest=~/bin/createStdGoWS mode=0755

- name: check if npm-check-updates is installed
  shell: npm list -g --depth 1 npm-check-updates
  ignore_errors: yes
  register: ncu
  check_mode: False
  changed_when: False

- name: install npm-check-updates if needed
  shell: npm install -g npm-check-updates
  when: ncu.rc != 0
