- name: create local Code config directory   
  file:
    path: "~/.config/{{item}}"
    state: directory
    mode: 0755

- name: create sync Code user-config directory     
  file:
    path: "~/Nextcloud/appconfig/usersettings/{{item}}/User"
    state: directory
    mode: 0755

    #- name: symlink the vscode user settings
    #  file:
    #    src: "~/Nextcloud/appconfig/usersettings/{{item}}/User"
    #    dest: "~/.config/{{item}}/User"
    #    state: link

- name: install extensions
  command: /usr/bin/code --force --install-extension {{ext_item}}
  loop:
    - stkb.rewrap
    - mutantdino.resourcemonitor
    - eamodio.gitlens
    - mhutchie.git-graph
    - GitLab.gitlab-workflow
    - vscode-snippet.Snippet
    - ms-vscode-remote.remote-containers
    - ms-vscode-remote.vscode-remote-extensionpack
    - ms-vsliveshare.vsliveshare
    - ms-vsliveshare.vsliveshare-audio
    - ms-vsliveshare.vsliveshare-pack
  loop_control:
    loop_var: ext_item
