#!/bin/sh

# source the env to lookup the SSH_AUTH_SOCK
. "$HOME/.ssh/environment-`hostname -s`"

CFGPATH=$HOME/Nextcloud/rustconfig
EXTPATH=$HOME/.config/vscode-rust-extensions
MOZPATH=$HOME/.config/vscode-rust-mozilla

mkdir -p $EXTPATH
mkdir -p $CFGPATH
mkdir -p $MOZPATH

DBUSPATH=`echo $DBUS_SESSION_BUS_ADDRESS | awk -F "=|," ' { print $2 } '`
docker run -it -d --rm --net=host \
    --ipc=host \
    --privileged \
    --security-opt=seccomp:unconfined \
    -v /tmp/.X11-unix:/tmp/.X11-unix  \
    -v `pwd`:`pwd` \
    -w `pwd` \
    -v $CFGPATH:/config \
    -v $EXTPATH:/config/vscode/.vscode \
    -v $MOZPATH:/config/vsc-mozilla \
    -v $HOME/Nextcloud/Entwicklung/git:/devhome/Nextcloud/Entwicklung/git:ro \
    -v $HOME/Nextcloud/Entwicklung/gnupg:/devhome/.gnupg \
    -v $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR \
    -e DISPLAY=unix$DISPLAY \
    -v $HOME/.gitconfig:/devhome/.gitconfig \
    -v $HOME/.kube:/devhome/.kube \
    -v $SSH_AUTH_SOCK:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent \
    -v $HOME/.git-credential-cache:/devhome/.git-credential-cache \
    -v /var/run/dbus:/var/run/dbus:ro \
    -v /run/docker.sock:/run/docker.sock:ro \
    -v /etc/machine-id:/etc/machine-id:ro \
    -v $DBUSPATH:/dbus \
    -e DBUS_SESSION_BUS_ADDRESS="unix:path=/dbus" \
    --device /dev/dri \
    --device /dev/snd \
    -e LANG=$LANG \
    -e HOSTUSER=`id -un` \
    -e HOSTGROUP=`id -gn` \
    -e HOSTUSERID=`id -u` \
    -e HOSTGROUPID=`id -g` \
    -e WORKSPACE=`pwd` \
    -e XAUTHORITY=/.XAUTHORITY -v $XAUTHORITY:/.XAUTHORITY \
    -e DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS \
    -e XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR \
    ulrichschreiner/vscode-rust:latest "$@"
